### ISSUE TITLE
Improve PGN parser

### ISSUE THREAD

**Issue by veloce** [lichess-org/dartchess#30]
~~Currently 2 tests are not passing:~~

Currently 1 test is not passing:

https://github.com/lichess-org/dartchess/blob/main/test/pgn_test.dart#L317

**Comment by Anupya** [comment]
What do you mean by passing because it seems like they are? (I'm on `main`) <img width="610" alt="Screenshot 2023-10-25 at 4 41 52 PM" src="https://github.com/lichess-org/dartchess/assets/24191989/d47d2586-ce07-421b-826a-b73a986778b9">

**Comment by veloce** [comment]
Sorry for late reply, I have too much notifications and I missed yours... Thanks for your interest in this project!
