### ISSUE TITLE
Bug in PGN parser

### ISSUE THREAD

**Issue by kuruhuru** [lichess-org/dartchess#38]
Hello!
I found a problem when loading pgn with '{\nsome comments' pattern. May be even inside '(' variation
I added example modified file wcc_2023_1.pgn
[wcc_2023_1.txt](https://github.com/lichess-org/dartchess/files/14897683/wcc_2023_1.txt)

I modified it here...
![image](https://github.com/lichess-org/dartchess/assets/24458142/d75db239-fe23-4f10-b3a8-5873886a18bf)

And when I run the following code the application hangs

```dart
void main(List<String> args) {
  final String data = File('bin/pgn/wcc_2023_1.pgn').readAsStringSync();
  final List<PgnGame<PgnNodeData>> games = PgnGame.parseMultiGamePgn(data);
  print('Games: ${games.length}');
  print('Game 1: ${games[0].makePgn()}');
}
```

**Comment by veloce** [comment]
The cause of the bug is `{`?

Feel free to make a PR with a fix and and new test case. Thanks!
